import { Inter } from "next/font/google";
import { ViewTransitions } from 'next-view-transitions'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ViewTransitions>
  );
}
